services:
  app:
    build: .
    container_name: mch-skr-app
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - BACKEND_URL=http://localhost:8000
    volumes:
      - ./dataset:/app/dataset

  dataset_downloader:
    build: .
    container_name: mch-skr-dataset
    profiles: ["init"]
    command: python scripts/download_dataset.py
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
    volumes:
      - ./dataset:/app/dataset